from typing import Optional, Protocol
from uuid import UUID

from src.domain.entities.user import User


class UserRepositoryPort(Protocol):
    async def save(self, user: User) -> User: ...
    async def get_by_id(self, user_id: UUID) -> Optional[User]: ...
    async def get_by_username(self, username: str) -> Optional[User]: ...
    async def get_by_email(self, email: str) -> Optional[User]: ...
